# Currently, cargo GitHub Action doesn't use the up to date (git) version of the cross, we have to specify the docker images manually.
# Cross creates an internal list of supported docker images when builds and pulls the images according to the list. Here we add the newly-supported ones.

[target.x86_64-unknown-freebsd]
image = "rustembedded/cross:x86_64-unknown-freebsd"
