---
verbosity: 'info'
address: 0.0.0.0:2053
table:
  start:
    if:
      qtype:
        - AAAA
    then:
    # A list of actions is allowed here
    - blackhole
    # The next tag to go
    - end
    else:
    - dispatch
  dispatch:
    if: any
    then:
    - query: domestic
    - check_secure
  check_secure:
    if:
      geoip:
        codes:
          - CN
    else:
    - query: secure
    - end

upstreams:
  114DNS:
    udp:
      addr: 114.114.114.114:53

  Ali:
    udp:
      addr: 223.6.6.6:53

  domestic:
    hybrid:
    - 114DNS
    - Ali

  cloudflare:
    https:
      no_sni: true
      name: cloudflare-dns.com
      addr: 1.1.1.1:443

  quad9:
    https:
      no_sni: true
      name: dns.quad9.net
      addr: 9.9.9.9:443

  secure:
    hybrid:
    - cloudflare
    - quad9
