---
verbosity: 'info'
cache_size: 4096
address: 0.0.0.0:2053
table:
- tag: start
  if:
    qtype:
      - AAAA
  then:
  # A list of actions is allowed here
  - disable
  # The next tag to go
  - end
  else:
  - dispatch
- tag: dispatch
  if: any
  then:
  - query: domestic
  - check_secure
- tag: check_secure
  if:
    geoip:
      codes:
        - CN
  else:
  - query: secure
  - end

upstreams:
- method:
    udp:
      addr: 114.114.114.114:53
  tag: 114DNS

- method:
    udp:
      addr: 223.6.6.6:53
  tag: Ali

- method:
    hybrid:
    - 114DNS
    - Ali
  tag: domestic

- method:
    https:
      no_sni: true
      name: cloudflare-dns.com
      addr: 1.1.1.1:443
  tag: cloudflare

- method:
    https:
      no_sni: true
      name: dns.quad9.net
      addr: 9.9.9.9:443
  tag: quad9

- method:
    hybrid:
    - cloudflare
    - quad9
  tag: secure
