name: "Build dcompass on various targets"
on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  cachix:
    if: (startsWith(github.event.head_commit.message, 'build:') || (github.event_name == 'schedule'))
    name: upload cachix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v8
        with:
          name: dcompass
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Run the general flake checks
      - run: nix flake check -vL

  create-release:
    if: (startsWith(github.event.head_commit.message, 'build:') || (github.event_name == 'schedule'))
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.current_time.outputs.formattedTime }}
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current_time
        with:
          format: YYYYMMDD_HHmm
          utcOffset: "+08:00"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ steps.current_time.outputs.formattedTime }}
          release_name: Automated build ${{ steps.current_time.outputs.formattedTime }}

  build-release:
    name: Build dcompass for ${{ matrix.target }}
    if: (startsWith(github.event.head_commit.message, 'build:') || (github.event_name == 'schedule'))
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, armv5te-unknown-linux-musleabi, x86_64-pc-windows-gnu, x86_64-apple-darwin, aarch64-unknown-linux-musl, x86_64-unknown-netbsd, i686-unknown-linux-musl, x86_64-unknown-freebsd]
        include:
          - target: x86_64-unknown-netbsd
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
          - target: armv5te-unknown-linux-musleabi
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: x86_64-unknown-freebsd

    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
        # Configure Nix to enable flakes
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Checkout
      uses: actions/checkout@v1

    - name: Update data files
      run: nix run .#update

    - name: Install upx for linux
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get install upx

    - name: Install upx for macos
      if: contains(matrix.os, 'macos')
      run: brew install upx

    - name: Install musl tools
      if: contains(matrix.target, 'musl')
      run: sudo apt-get install musl-tools

    - name: Install i686 tools
      if: contains(matrix.target, 'i686')
      run: sudo apt-get install binutils-i686-linux-gnu

    - name: Install aarch64 tools
      if: contains(matrix.target, 'aarch64')
      run: sudo apt-get install binutils-aarch64-linux-gnu

    - name: Install arm tools
      if: contains(matrix.target, 'arm')
      run: sudo apt-get install binutils-arm-linux-gnueabihf

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}

    - uses: actions-rs/install@v0.1
      with:
        crate: cross
        version: latest
        use-tool-cache: true

    - name: Cargo update
      run: cargo update

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build full
      run: |
        cross build --manifest-path ./dcompass/Cargo.toml --release --locked --target ${{ matrix.target }} --features "geoip-maxmind"
        if [[ "${{ matrix.target }}" == *"windows"* ]]
        then
          cp ./target/${{ matrix.target }}/release/dcompass.exe ./dcompass-${{ matrix.target }}-full.exe
        else
          cp ./target/${{ matrix.target }}/release/dcompass ./dcompass-${{ matrix.target }}-full
        fi
        cross build --manifest-path ./dcompass/Cargo.toml --release --locked --target ${{ matrix.target }} --features "geoip-cn"
        if [[ "${{ matrix.target }}" == *"windows"* ]]
        then
          cp ./target/${{ matrix.target }}/release/dcompass.exe ./dcompass-${{ matrix.target }}-cn.exe
        else
          cp ./target/${{ matrix.target }}/release/dcompass ./dcompass-${{ matrix.target }}-cn
        fi
        cross build --manifest-path ./dcompass/Cargo.toml --release --locked --target ${{ matrix.target }}
        if [[ "${{ matrix.target }}" == *"windows"* ]]
        then
          cp ./target/${{ matrix.target }}/release/dcompass.exe ./dcompass-${{ matrix.target }}-min.exe
        else
          cp ./target/${{ matrix.target }}/release/dcompass ./dcompass-${{ matrix.target }}-min
        fi

    - name: Strip x86
      if: contains(matrix.target, 'x86')
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]
        then
          strip ./dcompass-${{ matrix.target }}-full.exe
          strip ./dcompass-${{ matrix.target }}-cn.exe
          strip ./dcompass-${{ matrix.target }}-min.exe
        else
          strip ./dcompass-${{ matrix.target }}-full
          strip ./dcompass-${{ matrix.target }}-cn
          strip ./dcompass-${{ matrix.target }}-min
        fi

    - name: Strip arm
      if: contains(matrix.target, 'arm')
      shell: bash
      run: |
        arm-linux-gnueabihf-strip ./dcompass-${{ matrix.target }}-full
        arm-linux-gnueabihf-strip ./dcompass-${{ matrix.target }}-cn
        arm-linux-gnueabihf-strip ./dcompass-${{ matrix.target }}-min

    - name: Strip i686
      if: contains(matrix.target, 'i686')
      shell: bash
      run: |
        i686-linux-gnu-strip ./dcompass-${{ matrix.target }}-full
        i686-linux-gnu-strip ./dcompass-${{ matrix.target }}-cn
        i686-linux-gnu-strip ./dcompass-${{ matrix.target }}-min

    - name: Strip aarch64
      if: contains(matrix.target, 'aarch64')
      shell: bash
      run: |
        aarch64-linux-gnu-strip ./dcompass-${{ matrix.target }}-full
        aarch64-linux-gnu-strip ./dcompass-${{ matrix.target }}-cn
        aarch64-linux-gnu-strip ./dcompass-${{ matrix.target }}-min

    - name: Package
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]
        then
          upx ./dcompass-${{ matrix.target }}-full.exe || true
          upx ./dcompass-${{ matrix.target }}-cn.exe || true
          upx ./dcompass-${{ matrix.target }}-min.exe || true
        else
          upx ./dcompass-${{ matrix.target }}-full || true
          upx ./dcompass-${{ matrix.target }}-cn || true
          upx ./dcompass-${{ matrix.target }}-min || true
        fi

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: 'dcompass*'
        tag_name: build-${{ needs.create-release.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove-release:
    name: Clean up release(s)
    if: (startsWith(github.event.head_commit.message, 'build:') || (github.event_name == 'schedule'))
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - name: Clean-up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
